#!/usr/bin/env bash
# Build the local .env from the Go prototype's configuration plus freshly
# generated secrets.
#
#   ./scripts/bootstrap_env.sh [--reuse-prototype-key]
#
# Secrets are copied and generated but never printed: the summary is masked.
# --reuse-prototype-key takes the prototype's pseudonymization key instead of
# generating a new one, which makes pseudonyms comparable across the archive
# and the new collection. Without it the two periods describe the same people
# under different identifiers.
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_root"

prototype_directory="/home/eugene-panov/Projects/ideas/20260809_soulseek_node_radio/assets/collector"
prototype_environment="$prototype_directory/.env"
prototype_key="$prototype_directory/data/pseudonym-secret"

# The version the prototype reports at login. It is recognised by the server,
# which is the only reason parents are offered and anything is collected.
client_version_major=160
client_version_minor=3

reuse_prototype_key=false
if [[ "${1:-}" == "--reuse-prototype-key" ]]; then
    reuse_prototype_key=true
fi

if [[ -f .env ]]; then
    backup=".env.backup.$(date +%s)"
    cp .env "$backup"
    echo "Existing .env kept as $backup"
fi

if [[ ! -f "$prototype_environment" ]]; then
    echo "Prototype configuration not found at $prototype_environment" >&2
    exit 1
fi

soulseek_username="$(grep -E '^SOULSEEK_USERNAME=' "$prototype_environment" | cut -d= -f2-)"
soulseek_password="$(grep -E '^SOULSEEK_PASSWORD=' "$prototype_environment" | cut -d= -f2-)"

if [[ -z "$soulseek_username" || -z "$soulseek_password" ]]; then
    echo "Could not read the Soulseek credentials from the prototype" >&2
    exit 1
fi

if [[ "$reuse_prototype_key" == true ]]; then
    if [[ ! -r "$prototype_key" ]]; then
        echo "Prototype key not readable at $prototype_key" >&2
        exit 1
    fi
    privacy_hash_secret="$(xxd -p -c 64 "$prototype_key")"
    key_origin="reused from the prototype (pseudonyms match its archive)"
else
    privacy_hash_secret="$(openssl rand -hex 32)"
    key_origin="newly generated (pseudonyms will NOT match the archive)"
fi

clickhouse_password="$(openssl rand -hex 16)"

umask 077
cat > .env <<ENVIRONMENT
# Generated by scripts/bootstrap_env.sh — contains credentials, never commit.

SOULSEEK_USERNAME=${soulseek_username}
SOULSEEK_PASSWORD=${soulseek_password}
SOULSEEK_SERVER_HOST=server.slsknet.org
SOULSEEK_SERVER_PORT=2416
SOULSEEK_LISTENING_PORT=2234

# Recognised by the server; without it no distributed parent is offered.
SOULSEEK_CLIENT_VERSION_MAJOR=${client_version_major}
SOULSEEK_CLIENT_VERSION_MINOR=${client_version_minor}

CLICKHOUSE_HOST=clickhouse
CLICKHOUSE_PORT=8123
CLICKHOUSE_DATABASE=soulseek_charts
CLICKHOUSE_USER=soulseek_charts
CLICKHOUSE_PASSWORD=${clickhouse_password}

COLLECTOR_BATCH_SIZE=1000
COLLECTOR_FLUSH_INTERVAL_SECONDS=5

PRIVACY_HASH_SECRET=${privacy_hash_secret}

LOG_LEVEL=INFO
ENVIRONMENT

chmod 600 .env

echo "Wrote .env (mode $(stat -c '%a' .env)):"
echo "  SOULSEEK_USERNAME            ${soulseek_username}"
echo "  SOULSEEK_PASSWORD            <${#soulseek_password} characters, copied from the prototype>"
echo "  client version               ${client_version_major}.${client_version_minor}"
echo "  CLICKHOUSE_PASSWORD          <${#clickhouse_password} characters, generated>"
echo "  PRIVACY_HASH_SECRET          <${#privacy_hash_secret} characters, ${key_origin}>"
